apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
  labels:
    eks.amazonaws.com/component: coredns
    k8s-app: kube-dns
data:
  Corefile: |
    devops.com:53 {
      log
      errors
      health
      forward . 10.0.0.2
      cache 30
      reload
      loadbalance
    }
    # General server block for other domains (external queries)
    .:53 {
      errors
      health
      kubernetes cluster.local in-addr.arpa ip6.arpa {
        pods insecure
        fallthrough in-addr.arpa ip6.arpa
      }
      forward . /etc/resolv.conf  # Default system resolver
      prometheus :9153
      cache 30
      loop
      reload
      loadbalance
    }
