k8gb:
  dnsZone: "redis.devops.com" # dnsZone controlled by gslb
  edgeDNSZone: "devops.com" # main zone which would contain gslb zone to delegate
  edgeDNSServers: ["169.254.169.253"] # use this DNS server as a main resolver to enable cross k8gb DNS based communication
  clusterGeoTag: "us-east-1a" # used for places where we need to distinguish between differnet Gslb instances
  extGslbClustersGeoTags: "us-east-1b" # comma-separated list of external gslb geo tags to pair with

route53:
  enabled: true
  hostedZoneID: Z04904555KDVN04PK15L
  irsaRole: arn:aws:iam::194722417082:role/external-dns-role-tf # ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)

coredns:
  serviceType: LoadBalancer
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: nlb