apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: redis-cluster.devops.com
    meta.helm.sh/release-name: redis-cluster-a
    meta.helm.sh/release-namespace: redis-cluster
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  labels:
    app.kubernetes.io/instance: redis-cluster-a
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: redis-cluster
    app.kubernetes.io/version: 7.4.0
    helm.sh/chart: redis-cluster-11.0.3
  name: redis-cluster-a
  namespace: redis-cluster
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 172.20.34.245
  clusterIPs:
  - 172.20.34.245
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: tcp-redis
    nodePort: 30079
    port: 6379
    protocol: TCP
    targetPort: tcp-redis
  selector:
    app.kubernetes.io/instance: redis-cluster-a
    app.kubernetes.io/name: redis-cluster
  sessionAffinity: None
  type: LoadBalancer
