apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: redis-cluster-a-headless.redis.com
    meta.helm.sh/release-name: redis-cluster-a
    meta.helm.sh/release-namespace: redis-cluster
  labels:
    app.kubernetes.io/instance: redis-cluster-a
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: redis-cluster
    app.kubernetes.io/version: 7.4.0
    helm.sh/chart: redis-cluster-11.0.3
  name: redis-cluster-a-headless
  namespace: redis-cluster
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: tcp-redis
    port: 6379
    protocol: TCP
    targetPort: tcp-redis
  - name: tcp-redis-bus
    port: 16379
    protocol: TCP
    targetPort: tcp-redis-bus
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/instance: redis-cluster-a
    app.kubernetes.io/name: redis-cluster
  sessionAffinity: None
  type: ClusterIP